Status and progress message in UI when a deployment is started or stopped. Auto-updates on completion.
kwilteam/db-admin pull request #54
Opened 2024-10-23 20:04 UTC by tydangelo18

2024-10-25 17:08 UTC, KwilLuke commented on components/Firebird/Deployments/ExistingDeployment/SelectedDeployment/StatusStream.tsx
> +        }
Could you clean this up? Bit hard to read.

Something similar to how Martin organized here would be great: https://github.com/kwilteam/db-admin/blob/53d4bfe9caaad5e1a6c01ee8963b844f13b5a576/components/Firebird/Deployments/ExistingDeployment/SelectedDeployment/DeploymentStatusStream.tsx#L21

2024-11-01 22:39 UTC, KwilLuke reviewed
I am still a bit confused on what is going on here... might just be the end of friday feeling

2024-11-01 22:39 UTC, KwilLuke commented on hooks/firebird/use-event-stream.tsx
> +      return lastDeploymentStatus === DeploymentStatus.STARTING
What is the role of `lastDeploymentStatus`? Having a hard time following the logic here

2024-11-01 22:39 UTC, KwilLuke commented on hooks/firebird/use-event-stream.tsx
> +      return lastDeploymentStatus === DeploymentStatus.STARTING
When does this logic get hit?

2024-11-03 19:09 UTC, KwilLuke requested changes
Need to talk to you about a few things.

1. There is a slight issue in `useGetDeployment` where, when an instance switches from stopping to stopped, there is a brief moment where the node creation StatusStream appears.
2. I don't really understand the role of `lastDeploymentStatus` in `useEventStream`. Maybe we can talk about it live.

Also, I made some comments where I think readability should be improved.

2024-11-03 19:09 UTC, KwilLuke commented on hooks/firebird/use-event-stream.tsx
> +    }
Still need to discuss with you the role of `lastDeploymentStatus`... Reading this code, it is kind of confusing. Why do you need it?

Assuming you do need `lastDeploymentStatus`, why are you checking if `deploymentStatus` is equal to some variable and then setting it to that variable if true?

Why don't you just setLastDeploymentStatus to whatever deployment status is??

`setLastDeploymentStatus(deploymentStatus)`

2024-11-03 19:09 UTC, KwilLuke commented on hooks/firebird/use-event-stream.tsx
> +    return "follow_deployment"
Could you put this into something more readable like a switch statement? (Also, switch wouldn't require you to go through each case)

https://builtin.com/articles/switch-case-vs-if-else

2024-11-03 19:09 UTC, KwilLuke commented on components/Firebird/Deployments/ExistingDeployment/SelectedDeployment/StatusStream.tsx
> +    status === DeploymentStatus.STARTING
The nested ternary is quite hard to read.

Could you just create a utility function somewhere with a switch and then set it `eventDisplayNames` inside the functional component?

E.g.

```typescript
// utility function outside your functional component
const getEventDisplayNames = (status: DeploymentStatus) => {
  switch (status) {
    case DeploymentStatus.STARTING:
      return {
        [DeploymentEvents.START_INSTANCE]: "Starting Instance",
      };
    case DeploymentStatus.STOPPING:
      return {
        [DeploymentEvents.STOP_INSTANCE]: "Stopping Instance",
      };
    default:
      return {
        [DeploymentEvents.INIT_KEY_PAIR]: "Initializing Key Pair",
        [DeploymentEvents.CREATE_INSTANCE]: "Creating Instance",
        [DeploymentEvents.WAIT_INSTANCE_READY]: "Starting Instance",
        [DeploymentEvents.INSTALL_KWILD]: "Installing Kwil Daemon",
        [DeploymentEvents.REGISTER_DOMAIN]: "Registering Domain",
        [DeploymentEvents.FINALIZE_DEPLOYMENT]: "Finalizing Deployment",
      };
  }
};

// and then inside `StatusStream`: 
const eventDisplayNames = getEventDisplayNames(status);
```

2024-11-03 19:14 UTC, KwilLuke commented
IDK why my review posted twice. Sorry about that 😆

2024-11-05 16:27 UTC, tydangelo18 commented on components/Firebird/Deployments/ExistingDeployment/index.tsx
> +  useGetDeployment(id, eventStream.status)
@KwilLuke I understand why this makes sense, but, useGetDeployment is dependent on status

2024-11-05 16:28 UTC, KwilLuke commented on components/Firebird/Deployments/ExistingDeployment/index.tsx
> +  useGetDeployment(id, eventStream.status)
shit you're right

2024-11-06 21:29 UTC, KwilLuke commented on components/Firebird/Deployments/ExistingDeployment/SelectedDeployment/StatusStream.tsx
> +  let eventDisplayNames
Shouldn't this be a useState?

2024-11-06 21:35 UTC, KwilLuke approved these changes
lgtm

2024-11-06 21:36 UTC, merged